[mypy]
plugins = sqlalchemy.ext.mypy.plugin

[mypy-aioboto3.*]
ignore_missing_imports = True

[mypy-cassandra.*]
ignore_missing_imports = True

[mypy-asyncpg.*]
ignore_missing_imports = True

[mypy-aiomysql.*]
ignore_missing_imports = True

[mypy-snowflake.*]
ignore_missing_imports = True

[mypy-pyodbc.*]
ignore_missing_imports = True

[mypy-cx_Oracle.*]
ignore_missing_imports = True

[mypy-psycopg2.*]
ignore_missing_imports = True

[mypy-databricks.*]
ignore_missing_imports = True

[mypy-pyathena.*]
ignore_missing_imports = True

[mypy-trino.*]
ignore_missing_imports = True

[mypy-clickhouse_connect.*]
ignore_missing_imports = True

[mypy-pyhive.*]
ignore_missing_imports = True

[mypy-google.cloud.*]
ignore_missing_imports = True
